name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *'

jobs:
  dependabot:
    name: Dependabot Dependency Updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Dependabot
        uses: dependabot/fetch-metadata@v1
        with:
          dependency-name: "dependencies"
          update-type: "security"

  snyk:
    name: Snyk Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Install Snyk CLI
        run: npm install -g snyk
        
      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Snyk Test for Vulnerabilities
        run: snyk test

      - name: Snyk Monitor Project
        run: snyk monitor

  sonarcloud:
    name: SonarCloud Code Quality and Security Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v4.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=ais-project-poc
            -Dsonar.organization=fifa-um-si
            -Dsonar.host.url=https://sonarcloud.io
